server:
  port: 9000

spring:
  application:
    name: demo
  cloud:
    discovery:
      enabled: false
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/rest_crud
    username: postgres
    password: postgres